# Generated by Django 6.0 on 2025-12-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bassly', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
