# Generated by Django 6.0 on 2025-12-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmessage',
            name='subject',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
