# Generated by Django 5.2.7 on 2026-03-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0003_event_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeaturedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_by_users', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_events', to='accounts.user')),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
