name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: python manage.py check

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/bassly-web:latest .

      - name: Push image
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/bassly-web:latest
